### PR TITLE
feat: Change Popular Table Cache as Metadata Config Variable

### PR DESCRIPTION
**Pull request by alldoami**
Signed-off-by: Allison Doami <adoami@chanzuckerberg.com>

### Summary of Changes

Make it an option to update the popular table cache variable to be a variable in the metadata config so that those who want a longer/shorter cache can change it.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by alldoami** [comment]
@dorianj Thanks for pointing out this variable!

**Comment by alldoami** [comment]
Ah hm... @dorianj any suggestions on how to fix the tests? https://github.com/amundsen-io/amundsen/pull/1218/checks?check_run_id=2798523136

In order to keep it outside of the functions, I'll need the app context...

**Comment by dorianj** [comment]
I'm not sure what the right way to resolve this is. One thing we could do is attach the cache instance to the object in the constructor rather than at the  file, which would require doing the caching using inline calls rather than generators.

**Comment by alldoami** [comment]
@dorianj I'm not exactly sure what that means 😅 Does that mean to put the `@_CACHE.cache(` line above the `__init__`?

**Comment by mgorsk1** [comment]
I think we could wrap some functions into our custom decorator, which by default would be an pass-through noop decorator and could be configured to accept beaker cache manager in config class, sth like that:

```
from beaker.cache import CacheManager
from beaker.util import parse_cache_config_options


class NoCacheConfig:
    @staticmethod
    def my_decorator(func):
        def wrapper(*args, **kwargs):
            print("Something is happening before the function is called.")
            func(*args, **kwargs)
            print("Something is happening after the function is called.")

        return wrapper

    wrapper = my_decorator


class CacheConfig:
    cache_opts = {
        'cache.type': 'file',
        'cache.data_dir': '/tmp/cache/data',
        'cache.lock_dir': '/tmp/cache/lock'
    }

    cache = CacheManager(**parse_cache_config_options(cache_opts))

    wrapper = cache.cache('my_search_func', expire=3600)

cache_on = False

if cache_on:
    config = CacheConfig
else:
    config = NoCacheConfig


class Test:
    @config.wrapper
    def test(self, x):
        pass


t = Test()
t.test(1)
```

**Pull request closed without merging**
