### PR TITLE
Column Badge Documentation 

### PR DESCRIPTION
**Pull request by alldoami**
**Summary of Changes**
Added examples of how to use API for column badge

**Documentation**
Relevant to: amundsen-io/amundsenmetadatalibrary#273

### CODE REVIEW

**Comment by alldoami** [comment]
@feng-tao could you help me with merging non-related changes 😭

**Comment by feng-tao** [comment]
@alldoami could you rebase your local branch with the upstream master? lots of commits have been merged already which just lack in your local fork.

**Comment by alldoami** [comment]
@feng-tao i think I rebased correctly, but I need to sign now. I only want to sign the two commits that aren't signed but it goes back 78 in the instructions from DCO.

**Comment by dorianj** [comment]
this rebase didn't work -- there are still other merge commits present.

**Comment by alldoami** [comment]
@dorianj I do not see the files changed anymore though...

**Comment by feng-tao** [comment]
there is a unknown file ( amundsen-kube-helm/templates/helm/charts/elasticsearch-1.32.5.tgz) added to the pr.

**Comment by feng-tao** [comment]
@alldoami do you think you could open a new pr ? The long list of past commit concerns me a bit. Also you could sign the just one commit for the new pr. Sorry for the inconvenience.

**Comment by alldoami** [comment]
@feng-tao I could, but the same thing might happen as this is the "new" PR that I tried opening after https://github.com/amundsen-io/amundsen/pull/945 went awry.

**Review by feng-tao — APPROVED** [review]

**Pull request merged**
