### PR TITLE
Fix: Update Amundsen Common to 0.10.0

### PR DESCRIPTION
**Pull request by KevinDukelow5**
Critical front end components are breaking due to a mismatch in versions of the User model
Summary of Changes

Updates Frontend requirements for Amundsen Common from 0.9.0 to 0.10.0.
Tests
Documentation
CheckList

Make sure you have checked all steps below to ensure a timely review.

PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"

    In case you are adding a dependency, check if the license complies with the ASF 3rd Party License Policy.

PR includes a summary of changes.
PR adds unit tests, updates existing unit tests, OR documents why no test additions or modifications are needed.
In case of new functionality, my PR adds documentation that describes how to use it.

    All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
cc @danwom @allisonsuarez @Golodhros for FE pr

**Comment by verdan** [comment]
@KevinDukelow5, we've just published the new version of `common` with a new change in the User model required for the Lineage Graph Visualization. `amundsen-common==0.10.1`, can you please make sure to update this to the newer version? 

Also, I think you should be making this change for all the packages (frontend, metadata, search), so each one is aligned with this newer version.

**Comment by verdan** [comment]
@KevinDukelow5 please make sure to rebase from the latest master. This will fix your frontend build.

**Comment by verdan** [comment]
@KevinDukelow5 I believe we'll be moving to 0.11.0 now for all the packages.

**Comment by KevinDukelow5** [comment]
> @KevinDukelow5 I believe we'll be moving to 0.11.0 now for all the packages.

Yep, I saw that and updated frontend/search to the same

**Comment by verdan** [comment]
> > @KevinDukelow5 I believe we'll be moving to 0.11.0 now for all the packages.
> 
> Yep, I saw that and updated frontend/search to the same

Hmm, I still see 0.10.1 for both frontend and search

**Comment by KevinDukelow5** [comment]
> > > @KevinDukelow5 I believe we'll be moving to 0.11.0 now for all the packages.
> > 
> > 
> > Yep, I saw that and updated frontend/search to the same
> 
> Hmm, I still see 0.10.1 for both frontend and search

Oops, you're right, should be there now

**Pull request merged**
