### PR TITLE
style: Make consecutive paragraph visually distinguishable

### PR DESCRIPTION
**Pull request by dmohns**
Closes: https://github.com/amundsen-io/amundsen/issues/1255

### Summary of Changes

Scope of this PR to make consecutive PR in table description visually distinguishable. Originally, in the table description the `margin` CSS attribute was set to `0`. My assumption is this was done to make the table description be more compact given the relatively limited space that table descriptions can occupy. But w.r.t. to https://github.com/amundsen-io/amundsen/issues/1255 I think this causes more harm than good and hence the suggestion of this PR is to essentially revert the change and fallback to default `margin`. 

**Before:**
image

**After:**
image

### Tests

No tests should be affected as it's a style change.

### Documentation

N/A

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by Golodhros** [comment]
Could you add a screenshot of the before/after results?

**Comment by dmohns** [comment]
> Could you add a screenshot of the before/after results?

Updated description with screenshots 👍

**Comment by ozandogrultan** [comment]
Hi, when should we expect a review and potentially a merge for this PR? This will help us a lot with the styling of table descriptions and will increase the readability significantly.

**Review by Golodhros — APPROVED** [review]
LGTM

Thanks for doing this!

**Pull request merged**
