### PR TITLE
feat: Make default depth configurable for table lineage graph view

### PR DESCRIPTION
**Pull request by jsnb-devoted**
### Summary of Changes
For certain deployments the graph view can get unreadable when it displays nodes at too great a depth. The app hardcodes the table lineage graph depth to 5 currently. This PR makes that value configurable using the config-types pattern that the rest of the front end uses.

There is some discussion about the feature in a previous PR that I botched:
https://github.com/amundsen-io/amundsen/pull/2069

### Tests
Added a unit test for the function that gets the default graph depth

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by Golodhros** [comment]
> @Golodhros - I think I got this sorted out. I didn't see the instructions for signing/rebasing the commits until after I made the new PR. Going to close the old PR. Sorry about the thrash on that.

No prob!

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by Golodhros** [comment]
Fixes https://github.com/amundsen-io/amundsen/issues/2068

**Comment by Golodhros** [comment]
@jsnb-devoted could you remove my commit and fix it. yourself?

**Comment by jsnb-devoted** [comment]
> @jsnb-devoted could you remove my commit and fix it. yourself?

fixed and did a force push -- that should do it ya? @Golodhros

**Comment by Golodhros** [comment]
> > @jsnb-devoted could you remove my commit and fix it. yourself?
> 
> fixed and did a force push -- that should do it ya? @Golodhros

Yay, thanks!

**Comment by Golodhros** [comment]
@all-contributors please add @jsnb-devoted for code, ideas, question

**Comment by jsnb-devoted** [comment]
I'll fix these tests -- I need to update the function arguments in a few places

**Comment by jsnb-devoted** [comment]
hey @Golodhros -- I would love to actually get this fixed. I tried to sneak it in there by fixing the build errors I was seeing in CI but that isn't working. I'm trying to get the local dev environment figured out but npm is giving me all kinds of grief. I'll try to get it sorted out this week. The `npm install` keeps saying I'm not authenticated. I created an npm account and logged in and it still gives me this:
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
```

**Comment by Golodhros** [comment]
> hey @Golodhros -- I would love to actually get this fixed. I tried to sneak it in there by fixing the build errors I was seeing in CI but that isn't working. I'm trying to get the local dev environment figured out but npm is giving me all kinds of grief. I'll try to get it sorted out this week. The `npm install` keeps saying I'm not authenticated. I created an npm account and logged in and it still gives me this:
> 
> ```
> npm ERR! code E401
> npm ERR! Incorrect or missing password.
> npm ERR! If you were trying to login, change your password, create an
> npm ERR! authentication token or enable two-factor authentication then
> npm ERR! that means you likely typed your password in incorrectly.
> npm ERR! Please try again, or recover your password at:
> npm ERR!     https://www.npmjs.com/forgot
> npm ERR! 
> npm ERR! If you were doing some other operation then your saved credentials are
> npm ERR! probably out of date. To correct this please try logging in again with:
> npm ERR!     npm login
> ```

Oh, I see. I have seen somebody else reporting something similar, but it doesn't make a lot of sense (you shouldn't need an npm account to install dependencies).

I will try to check this out today and get back to you!

**Pull request closed without merging**
