### PR TITLE
perf: Update ModeDashboardLastModifiedTimestampExtractor to use Mode discovery api

### PR DESCRIPTION
**Pull request by youngyjd**
### Summary of Changes

Update ModeDashboardLastModifiedTimestampExtractor to use Mode discovery api. Metadata can be extracted in one api endpoint call instead of using two endpoints (it used to be one for spaces and one for reports)

Test added.

Updates for other Mode dashboard extractors come after

### Documentation

ModeDashboardLastModifiedTimestampExtractor config example in README

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely, including a title prefix.
- [x] PR includes a summary of changes.
- [x] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by feng-tao** [comment]
could you fix the DCO?

**Comment by feng-tao** [comment]
hey @dorianj , do you know why the CI is not auto-triggered but requires manual approve and run?
Screen Shot 2021-05-04 at 10 56 18 AM

**Comment by feng-tao** [comment]
```

53 files skipped due to complete coverage.
Coverage HTML written to dir build/coverage_html
Coverage XML written to file build/coverage.xml

Required test coverage of 70% reached. Total coverage: 74.45%

=============================== warnings summary ===============================
databuilder/models/dashboard/dashboard_table.py:95
  /home/runner/work/amundsen/amundsen/databuilder/databuilder/models/dashboard/dashboard_table.py:95: DeprecationWarning: invalid escape sequence \.
    m = re.match('([^./]+)://([^./]+)\.([^./]+)\/([^./]+)', table_id)

tests/unit/extractor/test_deltalake_extractor.py::TestDeltaLakeExtractor::test_create_last_updated
  /opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/pyspark/sql/context.py:77: DeprecationWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
    DeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================== 368 passed, 2 warnings in 43.62 seconds ====================
flake8 .
mypy .
Success: no issues found in 281 source files
isort ./ --check --diff
ERROR: /home/runner/work/amundsen/amundsen/databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_last_modified_timestamp_extractor.py Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/amundsen/amundsen/databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_last_modified_timestamp_extractor.py:before	2021-05-04 18:40:45.761179
+++ /home/runner/work/amundsen/amundsen/databuilder/tests/unit/extractor/dashboard/mode_analytics/test_mode_dashboard_last_modified_timestamp_extractor.py:after	2021-05-04 18:47:28.429239
@@ -8,7 +8,7 @@
 
 from databuilder import Scoped
 from databuilder.extractor.dashboard.mode_analytics.mode_dashboard_last_modified_timestamp_extractor import (
-    ModeDashboardLastModifiedTimestampExtractor
+    ModeDashboardLastModifiedTimestampExtractor,
 )
 from databuilder.models.dashboard.dashboard_last_modified import DashboardLastModifiedTimestamp
 
Skipped 2 files
make: *** [isort_check] Error 1
Makefile:23: recipe for target 'isort_check' failed
```

**Comment by youngyjd** [comment]
@feng-tao @allisonsuarez @dkunitsk @dorianj please take a look. I will have a few more PRs out to change other mode dashboard extractors.

**Review by allisonsuarez — APPROVED** [review]
LGTM!

**Comment by dorianj** [comment]
> hey @dorianj , do you know why the CI is not auto-triggered but requires manual approve and run?

Yeah, it's something Github changed: https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/

**Comment by dorianj** [comment]
Thanks for this fix, btw!

**Pull request merged**
