### PR TITLE
chore: migrate databuilder to neo4j-driver 4.4.5

### PR DESCRIPTION
**Pull request by allisonsuarez**
## NOT BW COMPATIBLE, UPGRADE [NEO4J DB >= 3.5.5](https://neo4j.com/developer/kb/neo4j-supported-versions/)
The newest driver is compatible with neo4j DB version >= 3.5 which was released in 2018.

- Migrated amundsen-databuilder to use neo4j-driver 4.4.5
- The driver for Metadata will be upgraded in a separate PR
**Issue:** https://github.com/amundsen-io/amundsen/issues/1008

### CODE REVIEW

**Review by kristenarmes — APPROVED** [review]
LGTM

**Review by feng-tao — COMMENTED** [review]
could you also change those version in docker file?

**Comment by allisonsuarez** [comment]
> could you also change those version in docker file?

wait which one? I just updated the neo4j python driver but the neo4j db version is fine since its >3.5

**Review by dkunitsk — APPROVED** [review]
great!

**Pull request merged**
