### PR TITLE
perf: update ModeDashboardQueryExtractor to discovery api

### PR DESCRIPTION
**Pull request by youngyjd**
### Summary of Changes

Update ModeDashboardQueryExtractor to use Mode discovery api. Test added.

### Documentation

ModeDashboardQueryExtractor config example in README

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely, including a title prefix.
- [x] PR includes a summary of changes.
- [x] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by youngyjd** [comment]
@dorianj Will this "First-time contributors need a maintainer to approve running workflows." go away once we change the default branch to main? Any plan when to make main as the default branch?

**Comment by youngyjd** [comment]
@allisonsuarez @dkunitsk @feng-tao PTAL

**Comment by feng-tao** [comment]
I update the default branch to main.

**Comment by feng-tao** [comment]
@youngyjd for all the mode ingestion change from legacy API to new discovery API, do we need to update the readme?

**Review by feng-tao — APPROVED** [review]

**Comment by youngyjd** [comment]
@feng-tao I updated the readme for every extractor that I have changed. Any more places that I need to check?

We reached an agreement with the Mode team about changes that they need to make on their discovery api:
```
1. Mode team adds last_run_status, last_run_timestamp, total_views_count, and space_token to the report discovery api
2. Provide a filter option for the Discovery API Reports and Report stats endpoints that will take a space token and return just the reports for that space
3. Nice to have but not required: include username in membership discovery api
```

For those extractors that cannot be fully switched to discovery api now before Mode team finishes their work, I will have a temporary fix for them.

**Comment by feng-tao** [comment]
@youngyjd that's great!

**Pull request merged**
