### PR TITLE
feat: Add bigquery column mode when consuming bigquery metadata

### PR DESCRIPTION
**Pull request by MrwanBaghdad**
### Summary of Changes

This PR intends to add the column mode when consuming column metadata for bigquery. The column mode indicates if the column is of an array type.

### Tests

Added a test case for a repeated nested field
### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by feng-tao** [comment]
cc @xuan616 to take a look

**Comment by xuan616** [comment]
The predefined length of column_type in rds model should be fine with the concatenation of type and mode. I do not have any concern from rds side. Thanks

just one nit: what do you think if we use type instead of mode as prefix.

**Comment by feng-tao** [comment]
@MrwanBaghdad ci fails

**Comment by MrwanBaghdad** [comment]
@xuan616  Thanks for the review.. I've incorporated your suggestions in the PR, please check.
@feng-tao  I fixed the CI issues

**Review by feng-tao — APPROVED** [review]
thanks @xuan616 for the review!

**Pull request merged**
