### PR TITLE
feat: Upgrade feast to 0.17

### PR DESCRIPTION
**Pull request by amommendes**
### Summary of Changes
Upgrade feast extractor with new Feast architecture

### Tests
- Update old tests and remove deprecated ones

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by feng-tao** [comment]
could you take a look at the test failure?

**Comment by amommendes** [comment]
> and there are a few binary files to check in the pr, any reason we need instead of mocking the data?

Hey @feng-tao ... They are parquet files created with example feast init command.. I think we could remove them, since we only need the metadata and not the data...

**Comment by feng-tao** [comment]
> > could you take a look at the test failure?
> 
> Hey @feng-tao. Thanks! Yeah, it fails on installing dependencies, since feast 0.12.1 is available only for python >=3.7... Is there some other problem that I did not see?

but given our CI runs for both 3.6,3.7, then it will always fail for py3.6?

**Comment by amommendes** [comment]
@feng-tao I removed the binary files adding setup and teardown methods to create and cleanup them on tests execution...

**Comment by feng-tao** [comment]
@amommendes let me ask around about py3.6 in the slack.

**Comment by amommendes** [comment]
@feng-tao any update on this? Do I need to push some new commit?

**Comment by dkunitsk** [comment]
Hi @amommendes. Can this wait until the end of the year (i.e. until the official EOL on 23rd of Dec). We'll be upgraded by then.

**Comment by amommendes** [comment]
> Hi @amommendes. Can this wait until the end of the year (i.e. until the official EOL on 23rd of Dec). We'll be upgraded by then.

Hey @dkunitsk , sure, great! thank you!

**Comment by amommendes** [comment]
Hey guys (@feng-tao , @dkunitsk), some update on this? 😀

**Comment by feng-tao** [comment]
will let @dkunitsk to comment on the current status

**Comment by dkunitsk** [comment]
@amommendes +1 from us, we're good to go.

**Comment by amommendes** [comment]
> maybe update to a later version of Feast @amommendes ? 

Sure, I would like to include feature service too... But I think could in a new PR

**Comment by feng-tao** [comment]
@dkunitsk https://github.com/amundsen-io/amundsen/pull/1673 for remove

**Comment by feng-tao** [comment]
@amommendes could you rebase with main branch? I just merge https://github.com/amundsen-io/amundsen/pull/1673

**Comment by feng-tao** [comment]
it should solve this ci error:
```
WARNING: Discarding https://files.pythonhosted.org/packages/98/cb/f77d9bd5f64246074af364cc30e20e3044c533890f3b67d30e89615c2fc5/ibm_db-3.0.1.tar.gz#sha256=a609e07295d16455d40df94ddd61b3d476606f5d44e3352103776e3ecbff185a (from https://pypi.org/simple/ibm-db/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ibm_db==3.0.1 (from amundsen-databuilder[all]) (from versions: 0.2.0, 0.2.6, 0.2.7, 0.2.9, 0.2.9.1, 0.3.0, 0.4.0, 0.4.1, 0.6.0, 0.7.0, 0.7.2, 0.7.2.1, 0.7.2.5, 0.8.0, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.4.1, 2.0.5, 2.0.5.1, 2.0.6.1, 2.0.7, 2.0.8a0, 2.0.8, 2.0.9, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1)
ERROR: No matching distribution found for ibm_db==3.0.1
Makefile:30: recipe for target 'install_deps' failed
make: *** [install_deps] Error 1
Error: Process completed with exit code 2.
```

**Comment by feng-tao** [comment]
could you rebase your pr? i could take a quick look and merge it once it is clear in CI.

**Comment by amommendes** [comment]
> could you rebase your pr? i could take a quick look and merge it once it is clear in CI.

@feng-tao it worked, I need to fix the linter on my side here 😅

**Comment by feng-tao** [comment]
```
======================== 466 passed in 85.31s (0:01:25) ========================
flake8 .
./tests/unit/extractor/test_feast_extractor.py:135: [E501] line too long (412 > 120 characters)
./tests/unit/resources/extractor/feast/fs/feature_view.py:32: [W291] trailing whitespace
./tests/unit/resources/extractor/feast/fs/feature_view.py:33: [W291] trailing whitespace
./tests/unit/resources/extractor/feast/fs/feature_view.py:35: [W291] trailing whitespace
make: *** [lint] Error 1
Makefile:11: recipe for target 'lint' failed
Error: Process completed with exit code 2.
```

**Comment by amommendes** [comment]
> ```
> ======================== 466 passed in 85.31s (0:01:25) ========================
> flake8 .
> ./tests/unit/extractor/test_feast_extractor.py:135: [E501] line too long (412 > 120 characters)
> ./tests/unit/resources/extractor/feast/fs/feature_view.py:32: [W291] trailing whitespace
> ./tests/unit/resources/extractor/feast/fs/feature_view.py:33: [W291] trailing whitespace
> ./tests/unit/resources/extractor/feast/fs/feature_view.py:35: [W291] trailing whitespace
> make: *** [lint] Error 1
> Makefile:11: recipe for target 'lint' failed
> Error: Process completed with exit code 2.
> ```

Yeah, I will fix it 😀

**Comment by amommendes** [comment]
@feng-tao I think now is correct

**Review by feng-tao — APPROVED** [review]

**Pull request merged**
