### PR TITLE
feat: search_service/config: fail on bad AWS ES config

### PR DESCRIPTION
**Pull request by jroof88**
When trying to set up the AWS Elasticsearch Config for the search service, if you don't have all the nessescary configuration values populated (host, region, credentials) the service will still set up properly but the client will be None. This commit changes the flow AwsSearchConfig to fail if all the values aren't populated which will result in the service not starting up and throwing this error properly that is a lot easier to debug. Without this, it is a bit of a rabbit chase to figure out why you can't connect to AWS ES.

### Summary of Changes

When trying to set up the AWS Elasticsearch Config for the search service, if you don't have all the nessescary configuration values populated (host, region, credentials) the service will still set up properly but the client will be None. This commit changes the flow `AwsSearchConfig` to fail if all the values aren't populated which will result in the service not starting up and throwing this error properly that is a lot easier to debug. Without this, it is a bit of a rabbit chase to figure out why you can't connect to AWS ES.

### Tests

I did not add any tests since this is a small control flow change and there isn't a `config_test.py`. If contributors feel like I should add one let me know and I can!

### Documentation

I added a blurb to the comment for `AwsSearchConfig` noting that you must have all of the configuration values populated for the start up will fail.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [X] PR includes a summary of changes.
- [X] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
@jroof88 could you fix the DCO (`git commit --amend --no-edit --signoff`) ?

**Comment by jroof88** [comment]
> @jroof88 could you fix the DCO (`git commit --amend --no-edit --signoff`) ?

Neat! Done!

**Comment by jroof88** [comment]
Looks like there actually is a test out there for this. Fixing.

**Comment by jroof88** [comment]
@feng-tao Tests are all cleaned up. Had to add an ENV var to `pytest` configuration. This is ready for another pass.

**Comment by feng-tao** [comment]
thanks @jroof88 !

**Comment by bbsbb** [comment]
@jroof88 - Can you elaborate on the intended behavior here? As far as I can see(and test), with this implementation any import of the config module would raise an exception if AWS_REGION is not set or credentials are missing, even if there is no intention to use AWS at all?

**Comment by madison-ookla** [comment]
> @jroof88 - Can you elaborate on the intended behavior here? As far as I can see(and test), with this implementation any import of the config module would raise an exception if AWS_REGION is not set or credentials are missing, even if there is no intention to use AWS at all?

Running into this exact issue myself. This seems like problematic behavior, as any non-AWS based setup is now broken by default.

**Comment by verdan** [comment]
> @jroof88 - Can you elaborate on the intended behavior here? As far as I can see(and test), with this implementation any import of the config module would raise an exception if AWS_REGION is not set or credentials are missing, even if there is no intention to use AWS at all?

@jroof88 , I am having this issue as well. Can you please help fix this?

**Comment by mgorsk1** [comment]
I propose to just revert this PR. I don't think that there is much that can be improved over previous iteration - when using AWS config you `need` to make sure that you have set up every env variable (hence `all(...)` condition). 

The way Python classes work is that if the code is not within class function it's always executed. That's why we cannot build such  strict/demanding flows in config classes.

This doc:
```
  You MUST have the environment variables AWS_REGION and PROXY_ENDPOINT populated and boto3 must be able to get
  credentials out of whatever environment you are running in. If any of these values turn out to be empty the config
  will fail and the service will not start up.
```
is true not just for the config but for amundsen in general.

**Comment by feng-tao** [comment]
sorry didn't catch this issue during review, let's revert the commit to unblock.

**Comment by feng-tao** [comment]
also the change should handle if you use AwsSearchConfig or no?

**Pull request merged**
