### PR TITLE
feat: add boolean config for adding publisher metadata to neo4j node

### PR DESCRIPTION
**Pull request by wli-brex**
### Summary of Changes

Adding a boolean config to control whether publisher metadata (e.g. ) need to be added as properties. Through this config (default True), we can [retain the data](https://github.com/amundsen-io/amundsen/blob/c9727bffaa6aeb53623ad2a808013e35c549f18a/databuilder/databuilder/task/neo4j_staleness_removal_task.py#L173) (won't get purged in async mode) when such metadata is not included.

### Tests

n/a

### Documentation

n/a

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Review by youngyjd — COMMENTED** [review]
We also don't need to raise an exception without publish_tag if this config is set to False

https://github.com/amundsen-io/amundsen/blob/3e3b0b189d6ce2af0d42bdc4838ce2903a4bca18/databuilder/databuilder/publisher/neo4j_csv_publisher.py#L159

**Comment by dkunitsk** [comment]
👁️

**Comment by dkunitsk** [comment]
I'd like to discourage this approach, which essentially tries to make some nodes "look" like they were created in the UI in order to avoid their deletion when using the stale data remover. 

There is already a better way for this, which we introduced some months back: https://github.com/amundsen-io/amundsen/tree/main/databuilder#using-node-and-relation-conditions-to-remove-stale-data

**Comment by wli-brex** [comment]
> I'd like to discourage this approach, which essentially tries to make some nodes "look" like they were created in the UI in order to avoid their deletion when using the stale data remover.
> 
> There is already a better way for this, which we introduced some months back: https://github.com/amundsen-io/amundsen/tree/main/databuilder#using-node-and-relation-conditions-to-remove-stale-data

@dkunitsk Thanks for the suggestions! I'll try it out first.

**Comment by youngyjd** [comment]
@dkunitsk Thanks for the feedback. It looks like the approach you pointed out is for removing stale nodes and relationships. This PR is for a different purpose and is backward compatible. The default value is still set to True.

Basically we back up these edited through UI nodes in a persistent storage. We want to make sure if our Neo4j dies, we can still restore those nodes created / edited from UI, using this csv_neo4j_publisher. We cannot use this version csv_neo4j_publisher and have to create our own version of the publisher to achieve it. We think it would be beneficial to the upstream too with the new config option. Happy to know your ideas.

**Comment by dkunitsk** [comment]
That's interesting that you back up neo4j into a different database and then use the publisher to re-publish back those nodes. To me this sounds like a bit of a unique setup that doesn't easily extend beyond Brex. Can I recommend subclassing the Neo4jCsvPublisher (making a BrexNeo4jCsvPublisher) which overrides `_create_props_body` to implement this behavior? We do exactly that at Lyft for a handful of similar publisher "hacks". 

If that's not feasible for you, feel free to go ahead with this approach.

**Comment by youngyjd** [comment]
> That's interesting that you back up neo4j into a different database and then use the publisher to re-publish back those nodes.

We have Neo4j running with persistent volume in kubernetes. However, if someone accidentally updates some descriptions and would like to restore then to previous states, it would be hard. neo4j-admin backup/restore tool requires downtime unless we opts in for Enterprise edition. Hence we decided to only back up neo4j nodes that have been edited on UI into a different database. With this setup, we can easily revert edited descriptions to whatever version customers want. We would also be able to track change histories for UI edited descriptions and collect some engagement metrics.

**Pull request merged**
