### PR TITLE
chore: Updates the mypy version to `0.782`

### PR DESCRIPTION
**Pull request by verdan**
### Summary of Changes

This PR updates the mypy version, as the older version does not work with Python 3.8, and we are already using the latest version in metadata repository.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by mgorsk1** [comment]
I've already bumped it to `0.812` here https://github.com/amundsen-io/amundsen/pull/1163 (alongside couple of different qa tools with more recent versions). not sure if makes sense to do it one by one, wdyt?

**Comment by verdan** [comment]
> I've already bumped it to `0.812` here #1163 (alongside couple of different qa tools with more recent versions) across all projects. not sure if makes sense to do it one by one, wdyt?

@mgorsk1  sure thing, I'm happy to drop this in favor of your PR. 
One remark though: would that make sense to only consolidate the requirements now, and use the version we are already using in any service? Updates to the latest versions go to a new PR? thoughts?

**Comment by mgorsk1** [comment]
agree, however when centralizing the versions of libraries in #1163 I have not introduced completely new versions. If 3 different projects used mypy with different versions, for `requirements-dev.txt` I went with the latest out of those 3, not something entirely new. Not sure what would be better way to do this.

**Comment by verdan** [comment]
ah, I see. this is perfect then. I also meant the same to use the latest of what we are already using in any service. 👍

**Comment by mgorsk1** [comment]
cool, I've updated the #1163 to be more explicit about approach I went with!

**Pull request closed without merging**
