### PR TITLE
fix: Amundsen Gremlin - issue 1946 - TornadoTransport init correction and moved order direction decr to desc

### PR DESCRIPTION
**Pull request by ggirodda**
### Summary of Changes

1. Removed useless parameters during `TornadoTransport` initialization
2. Moved Order.decr to Order.desc for gremlin queries using the deprecated order direction (the deprecated Order.decr doesn't work with Neptune)

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by feng-tao** [comment]
CI fails

**Comment by ggirodda** [comment]
Hi @feng-tao, thank you for your reply.
From what I see, the pipeline fails due to flake8 verification on two files that I didn't modify.
```
python3 -m flake8
./tests/conftest.py:16: [E501] line too long (128 > 120 characters)
./tests/conftest.py:20: [E501] line too long (131 > 120 characters)
Makefile:16: recipe for target 'lint' failed
make: *** [lint] Error 1
Error: Process completed with exit code 2.
```

**Comment by sangram23** [comment]
(amundsen4_gremlin) [ec2-user@ip-10-30-204-31 metadata]$ sudo systemctl status egdh_metadata_gremlin -l
● egdh_metadata_gremlin.service - EGDH metadata service
   Loaded: loaded (/usr/lib/systemd/system/egdh_metadata_gremlin.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-11-17 07:44:51 UTC; 38s ago
 Main PID: 19061 (python)
   CGroup: /system.slice/egdh_metadata_gremlin.service
           └─19061 /home/ec2-user/amundsen4_gremlin/bin/python /home/ec2-user/amundsen-gremlin/metadata/metadata_service/metadata_wsgi.py

Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: /home/ec2-user/amundsen4_gremlin/lib/python3.7/site-packages/marshmallow/schema.py:388: ResourceWarning: unclosed file <_io.FileIO name=35 mode='rb' closefd=True>
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: self.dump_only = set(dump_only) or set(self.opts.dump_only)
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: ResourceWarning: Enable tracemalloc to get the object allocation traceback
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: /home/ec2-user/amundsen4_gremlin/lib/python3.7/site-packages/marshmallow/schema.py:388: ResourceWarning: unclosed file <_io.FileIO name=36 mode='wb' closefd=True>
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: self.dump_only = set(dump_only) or set(self.opts.dump_only)
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: ResourceWarning: Enable tracemalloc to get the object allocation traceback
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: /home/ec2-user/amundsen4_gremlin/lib/python3.7/site-packages/marshmallow/schema.py:388: ResourceWarning: unclosed <ssl.SSLSocket fd=37, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.30.204.31', 48784), raddr=('10.30.204.194', 8182)>
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: self.dump_only = set(dump_only) or set(self.opts.dump_only)
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: ResourceWarning: Enable tracemalloc to get the object allocation traceback
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_metadata4[19061]: 2022-11-17T07:45:22+0000.137 [INFO] _internal._log:225 (19061:Thread-4) - 127.0.0.1 - - [17/Nov/2022 07:45:22] "GET /table/glue://na_usa_ecs_na-bi-prod_awsglue.awsglue_database_jbtest/aws_glue_jbtest HTTP/1.1" 200 -
(amundsen4_gremlin) [ec2-user@ip-10-30-204-31 metadata]$ sudo systemctl status egdh_frontend_gremlin -l
● egdh_frontend_gremlin.service - EGDH frontend service
   Loaded: loaded (/usr/lib/systemd/system/egdh_frontend_gremlin.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-11-17 07:29:47 UTC; 16min ago
 Main PID: 16429 (python)
   CGroup: /system.slice/egdh_frontend_gremlin.service
           └─16429 /home/ec2-user/amundsen4_gremlin/bin/python /home/ec2-user/amundsen-gremlin/frontend/amundsen_application/wsgi.py

Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: File "/home/ec2-user/amundsen4_gremlin/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: data, many=many, partial=partial, unknown=unknown, postprocess=True
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: File "/home/ec2-user/amundsen4_gremlin/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: raise exc
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: marshmallow.exceptions.ValidationError: {'row_count': ['Unknown field.']}
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: 2022-11-17T07:45:22+0000.146 [DEBUG] action_log_callback.on_post_execution:70 (16429:Thread-30) - Calling callbacks: [<function logging_action_log at 0x7ff321b9eae0>]
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: 2022-11-17T07:45:22+0000.146 [DEBUG] action_log_callback.logging_action_log:85 (16429:Thread-30) - logging_action_log: ActionLogParams(command='_get_table_metadata', start_epoch_ms=1668671121941, end_epoch_ms=1668671122146, user='root', host_name='ip-10-30-204-31.ec2.internal', pos_args_json='[]', keyword_args_json='{"table_key": "glue://na_usa_ecs_na-bi-prod_awsglue.awsglue_database_jbtest/aws_glue_jbtest", "index": "0", "source": "inline_search"}', output='{"tableData": {}, "msg": "Encountered exception: {\'row_count\': [\'Unknown field.\']}", "status_code": 500}', error=None)
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: /home/ec2-user/amundsen4_gremlin/lib/python3.7/site-packages/flask/json/__init__.py:179: DeprecationWarning: Importing 'itsdangerous.json' is deprecated and will be removed in ItsDangerous 2.1. Use Python's 'json' module instead.
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: rv = _json.dumps(obj, **kwargs)
Nov 17 07:45:22 ip-10-30-204-31.ec2.internal egdh_frontend4[16429]: 2022-11-17T07:45:22+0000.147 [INFO] _internal._log:225 (16429:Thread-30) - 10.187.63.84 - - [17/Nov/2022 07:45:22] "GET /api/metadata/v0/table?key=glue%3A%2F%2Fna_usa_ecs_na-bi-prod_awsglue.awsglue_database_jbtest%2Faws_glue_jbtest&index=0&source=inline_search HTTP/1.1" 500 -
(amundsen4_gremlin) [ec2-user@ip-10-30-204-31 metadata]$

**Comment by Golodhros** [comment]
@ggirodda any news on this?

**Comment by ggirodda** [comment]
Hi @Golodhros and @sangram23 , sorry for the late answer.
The problem is caused by some customization to the table and column structure that I made to the my fork of amundsen. Those modifications are not related to this error. I'll update the pull request with the isolated correction

**Comment by ggirodda** [comment]
I created a new Pull Request, because I can't change the source branch of this one. The source branch is not yet the master branch.
Here is the new PR:
https://github.com/amundsen-io/amundsen/pull/2104
I'm closing this one

**Pull request closed without merging**
