### PR TITLE
test: Add Python 3.8 and 3.9 databuilder CI

### PR DESCRIPTION
**Pull request by Fokko**
### Summary of Changes

Ran the databuilder locally using 3.9 and it works fine, would be a pity to not add this as a supported version

### Tests

Added the versions to the `setup.py` and the CI itself.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by dorianj** [comment]
LGTM 

Could you also add 3.9 to https://github.com/amundsen-io/amundsen/blob/main/.github/workflows/noop_pull_request.yml ? thanks!

**Comment by dorianj** [comment]
After this lands (including that noop change), we will enforce the check on our side.

Also, are there any places in the docs where this should change?

**Comment by Fokko** [comment]
@dorianj Thanks for looking into this. I've checked the docs, and could not find anything that should be changed. I've added the 3.9 to the noop workflow as well.

**Review by dorianj — APPROVED** [review]
Thanks for the submission!!

**Comment by dorianj** [comment]
also, if you're feeling like it, would super appreciate a PR to make the front-end service work with newer versions of Python. there are some real failures there (that the tests catch!), though, so won't be quite as trivial

**Comment by dorianj** [comment]
Uh oh, looks like the build failure is real

**Comment by Fokko** [comment]
@dorianj Happy to bump the front end as well. But let me first dig into this error, looks like something real indeed.

**Comment by Fokko** [comment]
I'm unable to reproduce this locally or in an Ubuntu docker container. I think it has to do with the sequencing. `numpy` is installed in the same run, as it where tries to bind with the headers.

**Comment by dorianj** [comment]
You're welcome to hit me up on the slack!

There might be a discrepancy between the stuff that's in requirements, and that which is in setup.py which might be causing problems

**Comment by Fokko** [comment]
There is an issue with `pyarrow`, which is being brought in by `feast`, which is pinned at `0.8.0`: https://github.com/amundsen-io/amundsen/blob/main/databuilder/setup.py#L76. This pulls in `pyarrow<0.16.0,>=0.15.1`: https://github.com/feast-dev/feast/blob/v0.8.0/sdk/python/setup.py#L45. Which does not support Python 3.8+: https://github.com/apache/arrow/issues/5987

I can bump feast in another PR, to keep the PR's nice and small. WDYT?

**Pull request closed without merging**
