### PR TITLE
fix: open file in read mode and close on cleanup for ElasticsearchPublisher

### PR DESCRIPTION
**Pull request by m1racoli**
* fix: open file in read mode
* fix: close file handler on cleanup

### Summary of Changes

Since we only read from the file, we do not need to open it in write mode. Furthermore we close the file on cleanup in order to avoid issues with open file handlers. In particular this affects the automatic cleanup of [temporary directories](https://docs.python.org/3.10/library/tempfile.html#tempfile.TemporaryDirectory) containing the file.

### Tests

This affects low level aspect of how we open and close files, which might be beyond the scope of tests.

### Documentation

Nothing to document as there is not effective change in behaviour.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by m1racoli** [comment]
New PR based on https://github.com/amundsen-io/amundsen/pull/1772

**Comment by m1racoli** [comment]
Can someone take a look please?

**Comment by allisonsuarez** [comment]
@m1racoli have you considered moving to use the new elasticsearch task? https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py

**Review by allisonsuarez — APPROVED** [review]

**Comment by m1racoli** [comment]
> @m1racoli have you considered moving to use the new elasticsearch task? https://github.com/amundsen-io/amundsen/blob/main/databuilder/databuilder/task/search/search_metadata_to_elasticsearch_task.py

Oh, that's interesting. We will take a look. Thanks!

**Comment by m1racoli** [comment]
Independent of the new class, what's missing for this PR to be merged?

**Pull request closed without merging**
