### PR TITLE
fix: #1572 - make where_clause_suffix an actual suffix

### PR DESCRIPTION
**Pull request by delwaterman**
Signed-off-by: Orion Delwaterman <delwaterman@gmail.com>

### Summary of Changes

Fixes https://github.com/amundsen-io/amundsen/issues/1572

Changes the config of `RedshiftMetadataExtractor` `where_clause_suffix` to not require a user to include a `WHERE` statement in their sql partial. This follows the behavior of `PostgresMetadataExtractor`, and seems more consistent with the variable name `where_clause_suffix` by treating the partial as a _suffix_ to a where clause.

This will be a breaking change for anyone using redshift extractor (so probably will need a minor version bump). That being, IMHO, it's better to make the behavior follow expected patterns rather than ask users to hunt through source code to determine why their query is breaking (which happened to me).

### Tests

`databuilder/tests/unit/extractor/test_redshift_metadata_extractor.py`

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by dkunitsk** [comment]
Redshift extractor is reasonably popular and the style fix isn't worth breaking ingestor, imho. `where True` is always a workaround.

**Comment by delwaterman** [comment]
If I may, I lost 1 hour of development tracking down this issue, which doesn't feel like a lot, but forcing a user to dig through source code to understand how to use a public API is bad form. Personally it led me to trust this code base less, because it felt sloppy. I am not trying to pick a fight, but I am trying to tell my experience as a new developer using the project

That being said, why don't we do a comprimise, and support the old pattern, with a deprecation warning:

```python
if where_clause_suffix.lower().startswith("where"):
    logger.Warn("you no longer need to begin with 'where' in your suffix")
    where_clause = where_clause_suffix
else:
    where_clause = f"where {where_clause_suffix}"
```

**Comment by verdan** [comment]
This is kind of an issue we had for Postgres, and we fixed it here: https://github.com/amundsen-io/amundsen/commit/6cf8965ce8b065cc68be8fe021b1e7496b4b7716#diff-01ee0656007972e26ae47d9003cf877aefa524b6e91a6bf6b72035892ba9b757R47

So a suggestion is to make the `where_clause_suffix` a real suffix, what @delwaterman is suggesting, and make the default value as `true`.

**Comment by delwaterman** [comment]
Ok I will do the update

**Comment by delwaterman** [comment]
@verdan @dkunitsk This is now ready

**Comment by delwaterman** [comment]
Bump

**Comment by delwaterman** [comment]
bump

**Review by dkunitsk — APPROVED** [review]

**Pull request merged**
