### PR TITLE
docs: Edit docs for clarity and fix typos

### PR DESCRIPTION
**Pull request by Mich45**
### Documentation

This PR improves the Installation Guide for clarity and fixed some typos.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by Golodhros** [comment]
@all-contributors please add @Mich45  for 📖

**Comment by Golodhros** [comment]
https://github.com/all-contributors please add @Mich45 for doc

**Comment by Golodhros** [comment]
@all-contributors please add @Mich45 for doc

**Comment by Mich45** [comment]
Hi @Golodhros, I have signed the commits now.

**Pull request merged**
