### PR TITLE
fix: Update dbt_extractor - issue-1615

### PR DESCRIPTION
**Pull request by teoria**
# Changed: get columns from catalog, not manifest as manifest sometimes does not have all columns

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by falkzeh** [comment]
Tested locally - lgtm

**Comment by feng-tao** [comment]
@teoria could you fix the linting error?
```
Required test coverage of 70% reached. Total coverage: 76.14%
================== 464 passed, 7 warnings in 66.32s (0:01:06) ==================
flake8 .
./databuilder/extractor/dbt_extractor.py:290: [W291] trailing whitespace
Makefile:11: recipe for target 'lint' failed
make: *** [lint] Error 1
Error: Process completed with exit code 2.

```

**Comment by teoria** [comment]
@feng-tao  updated

**Review by petehanssens — COMMENTED** [review]
@feng-tao this works... apologies for the delay in getting back to you on it!

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
@teoria there is one more lint failure, could you rebase with main and take a look?

**Comment by feng-tao** [comment]
thanks @teoria :)

**Comment by feng-tao** [comment]
and thanks @petehanssens for the verify

**Pull request merged**
