### PR TITLE
fix: bump databuilder version

### PR DESCRIPTION
**Pull request by dkunitsk**
Forgot to bump version here: https://github.com/amundsen-io/amundsen/pull/1235

Proposing a major bump given the bw-incompatibility in above PR.

### CODE REVIEW

**Comment by dkunitsk** [comment]
@feng-tao could you approve and merge

**Comment by dkunitsk** [comment]
sorry i will fix the DCO breaks

**Review by dorianj — APPROVED** [review]

**Review by feng-tao — APPROVED** [review]

**Comment by dkunitsk** [comment]
@feng-tao if you could release databuilder 5.0.0 would be awesome

**Comment by feng-tao** [comment]
latest version is published: https://pypi.org/project/amundsen-databuilder/

**Pull request merged**
