### PR TITLE
docs: Fix links to point to correct branch and mono-repo

### PR DESCRIPTION
**Pull request by cooper6581**
### Summary of Changes

Change links that used to point to `master` to `main` and update them to use the mono repo directory structure.

### Tests

N/A

### Documentation

Updated links, no other changes made.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [na] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [na] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by feng-tao** [comment]
thanks for the fix, could you fix the dco check?

**Comment by cooper6581** [comment]
Sorry about that, done!

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
@cooper6581  sorry for the wait, do you think you could help to rebase and resolve the conflict in this pr? thanks, will merge once it is fixed.

**Comment by cooper6581** [comment]
No prob, should be good now.

**Review by feng-tao — APPROVED** [review]

**Pull request merged**
