### PR TITLE
fix: Database filter to return string, not object

### PR DESCRIPTION
**Pull request by sewardgw**
Signed-off-by: Grant Seward <grant@stemma.ai>

### Summary of Changes

Previously, when selecting the database from the table details page the value placed into the `source` field was an object, not a string. This PR updates the value being passed to be the actual value of the database.

Previous:

Screen Shot 2021-04-23 at 10 30 32 AM

Current:

Screen Shot 2021-04-23 at 10 30 39 AM

This is inline with how other filters are being passed, for example, dashboard and table tags: https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/components/Tags/TagInfo/index.tsx#L63

### Documentation

N/A

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely, including a title prefix.
- [ ] PR includes a summary of changes.
- [ ] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by markgrover** [comment]
Awesome, thanks! Out of scope of this PR, but it'd be great to make this is a dropdown in the future because most orgs only have a handful of these sources (like Bigquery, Redshift, etc.) and we should get a list and show them. We'd also need a default all in that case.

**Comment by Golodhros** [comment]
> Awesome, thanks! Out of scope of this PR, but it'd be great to make this is a dropdown in the future because most orgs only have a handful of these sources (like Bigquery, Redshift, etc.) and we should get a list and show them. We'd also need a default all in that case.

There is new stuff coming soon for this, they are still figuring out the proposal, but stay tuned!

**Comment by dorianj** [comment]
Test failure is real (lint), but this LGTM

**Pull request merged**
