### PR TITLE
Modified RuntimeError to NotFoundException in neo4j_proxy (metadata s…

### PR DESCRIPTION
**Pull request by aparna-cimpress**
Try block in `_put_resource_description` & `put_column_description` method in `neo4j_proxy` in metadata service throws RuntimeError when table or column doesn’t exist. I have changed it to throw NotFoundException with 404 status code.

### CODE REVIEW

**Comment by aparna-cimpress** [comment]
Try block in _put_resource_description & put_column_description method throws RuntimeError when table or column doesn’t exist. I have changed it to throw NotFoundException with 404 status code.

**Comment by dorianj** [comment]
Hey, can you please submit this as a PR against the `main` branch, with the files changed directly (rather than across the sub-repos)? The Amundsen project [moved to a monorepo](https://github.com/amundsen-io/rfcs/pull/31).

**Comment by aparna-cimpress** [comment]
Hey, @dorianj I tried that way but I couldn't perform` git add `. Is there any guide to follow the steps or if would be great if someone can help me here?

**Comment by aparna-cimpress** [comment]
Hey @dorianj I have opened another PR here 
https://github.com/amundsen-io/amundsen/pull/1028

**Pull request closed without merging**
