### PR TITLE
fix: bump pandas version limit

### PR DESCRIPTION
**Pull request by HaoXuAI**
## Motivation and Context

Follow up on PR: https://github.com/amundsen-io/amundsen/pull/1858, this bump the pandas upper limit to 2.2.2.

### CheckList
* [x] PR title addresses the issue accurately and concisely
* [ ] Updates Documentation and Docstrings
* [ ] Adds tests
* [ ] Adds instrumentation (logs, or UI events)

### CODE REVIEW

**Comment by kristenarmes** [comment]
hi @HaoXuAI thanks for the PR, I approved the checks to run, but based on the failures it looks like the `feast` version might be too low if you want to try to upgrade that version too

**Comment by HaoXuAI** [comment]
> hi @HaoXuAI thanks for the PR, I approved the checks to run, but based on the failures it looks like the `feast` version might be too low if you want to try to upgrade that version too

@kristenarmes thanks. trying to bump the version for feast

**Review by kristenarmes — APPROVED** [review]
thanks for the persistence in fixing the errors, LGTM

**Comment by HaoXuAI** [comment]
@kristenarmes thanks! When would you cut a release to make the change alive?

**Comment by kristenarmes** [comment]
@HaoXuAI sorry should have commented that on the original PR, could you bump the version [here](https://github.com/amundsen-io/amundsen/blob/main/databuilder/setup.py#L8)? and then I will approve/cut the release

**Comment by HaoXuAI** [comment]
> @HaoXuAI sorry should have commented that on the original PR, could you bump the version [here](https://github.com/amundsen-io/amundsen/blob/main/databuilder/setup.py#L8)? and then I will approve/cut the release

no worries and yeah for sure, `7.5.6` or `7.4.7`?

**Comment by kristenarmes** [comment]
> no worries and yeah for sure, `7.5.6` or `7.4.7`?

let's do `7.5.0`, thanks!

**Comment by HaoXuAI** [comment]
> > no worries and yeah for sure, `7.5.6` or `7.4.7`?
> 
> let's do `7.5.0`, thanks!

sounds good. updated here: https://github.com/amundsen-io/amundsen/pull/2256

**Pull request merged**
