### PR TITLE
docs: add Instacart to readme

### PR DESCRIPTION
**Pull request by instazackwu**
### Summary of Changes

Add [Instacart](https://www.instacart.com/) as a user of Amundsen

### Documentation

Changed the [README.md](https://github.com/lyft/amundsen/blob/master/README.md)

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely, including a title prefix.
- [x] PR includes a summary of changes.
- [x] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]
thanks!

**Comment by feng-tao** [comment]
@instazackwu  how's the experience so far? cc @Alagappan as well

**Comment by instazackwu** [comment]
Thanks @feng-tao ! It's great - we have a lot of work to do on our side in terms of easily linking upstream process DAGS / pointers to Git code, but people are already getting value out of the base system we have in place. Appreciate your help and the rest of the team's help in getting this set up!

**Comment by feng-tao** [comment]
> Thanks @feng-tao ! It's great - we have a lot of work to do on our side in terms of easily linking upstream process DAGS / pointers to Git code, but people are already getting value out of the base system we have in place. Appreciate your help and the rest of the team's help in getting this set up!

thanks for sharing that ! and great to have you and your team to join the Amundsen community!

**Comment by Alagappan** [comment]
@instazackwu Great to hear that people at finding value in Amundsen. Thanks for the update!

**Comment by markgrover** [comment]
Indeed, welcome!

**Pull request merged**
