### PR TITLE
fix: typo aws_secret_access_key in neptune csv publisher

### PR DESCRIPTION
**Pull request by iamtodor**
fix typo aws_secret_access_key in neptune csv publisher

### CODE REVIEW

**Comment by mgorsk1** [comment]
amundsen databuilder has been migrated to this repository directly and it no longer exists through the concept of submodule. if your issue is still current then feel free to modify files in https://github.com/amundsen-io/amundsen/tree/main/databuilder and updating this pr

**Review by mgorsk1 — CHANGES_REQUESTED** [review]
Thanks for the PR @iamtodor. Amundsen databuilder has been migrated to this repository directly and it no longer exists through the concept of submodule (the repo for which you bump submodule is deprecated). if your issue is still current then feel free to modify files in https://github.com/amundsen-io/amundsen/tree/main/databuilder and re-raising this PR.

**Comment by iamtodor** [comment]
@mgorsk1 hello, thank you for your answer. I'm a bit confused. Could you please help me to figure out what is the proper way to contribute? I forked this repo to my profile https://github.com/iamtodor/amundsen and it shows me amundsendatabuilder is a submodule, not a part of the amundsen project.
image

**Comment by mgorsk1** [comment]
sure thing - you are looking on `master` branch that is deprecated too, the latest code is on `main` :)

**Comment by iamtodor** [comment]
@mgorsk1 omg :D 
Thank you so much, for pointing it out!
I've created a new PR https://github.com/amundsen-io/amundsen/pull/1134 and I'll close this one as irrelevant

**Pull request closed without merging**
