### PR TITLE
feat: Add customization point for footer logo title

### PR DESCRIPTION
**Pull request by shuichiro-makigaki**
### Summary of Changes

In addition to a customization point for the header logo title (58472343), the footer's logo title should also be customizable.

Requested by: https://github.com/amundsen-io/amundsenfrontendlibrary/pull/953#issuecomment-831803247

### Tests

Tests for the getter method are added.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by NiravLangaliya** [comment]
Hello @shuichiro-makigaki , Thank you for creating this pull request and submitting change. but I would like to request you that 
Would you please also consider these changes driven from config file?

https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/static/templates/index.html#L10
https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/static/js/pages/SearchPage/constants.ts#L7
https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/static/js/pages/AnnouncementPage/index.tsx#L61
https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/pages/BrowsePage/constants.ts
https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/static/js/pages/BrowsePage/index.spec.tsx#L23
https://github.com/amundsen-io/amundsen/blob/main/frontend/amundsen_application/static/js/pages/HomePage/constants.ts
https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/static/js/pages/ProfilePage/index.spec.tsx#L316
https://github.com/amundsen-io/amundsen/blob/4db357a266b244a3f1c176a86e1d2e5a262726ac/frontend/amundsen_application/static/js/pages/ProfilePage/index.tsx#L299

**Comment by Golodhros** [comment]
Hi @shuichiro-makigaki,

Thanks for creating this PR and contributing to Amundsen.

I have synced with the rest of maintainers and we agreed that adding more of this customizations to modify the name of the project doesn't align with the direction we want to take. Specifically, we want to:
- Allow users that work with Amundsen to recognize the project once they move to another company
- Foster recognition of the project across companies, so we can get more contributors and ensure the long term life of the project
- Avoid adding complexity when it is not necessary

For this reasons, we have decided to reject this PR and all the rest of suggestions made by @NiravLangaliya.

We still think users could get the same result of renaming Amundsen to something else by overriding Frontend files or even forking the project, and that's OK. We just don't want to include these options as part of the project configuration.

**Comment by shuichiro-makigaki** [comment]
@Golodhros No problem. That sounds reasonable. I just thought my Pull Request was too ad-hoc, and adding more custom points makes Amundsen complex unnecessarily. It does not make users happy, as well as contributors.

One thing I am a little worried about is the similar Pull Requests will be made again by other contributors because many users have similar needs... We need some statements from project owners about frontend customization.

**Comment by Golodhros** [comment]
Thanks for your understanding!

> One thing I am a little worried about is the similar Pull Requests will be made again by other contributors because many users have similar needs... We need some statements from project owners about frontend customization.

That's a good point! I will try to find a spot to mention this in our docs or in the code itself.

**Pull request closed without merging**
