### PR TITLE
docs: update faq.md

### PR DESCRIPTION
**Pull request by mgorsk1**
Signed-off-by: mgorsk1 <gorskimariusz13@gmail.com>

### Summary of Changes

Updates the documentation of Neo4j vs. Atlas

### Documentation

faq.md

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely, including a title prefix.
- [x] PR includes a summary of changes.
- [x] My commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"

### CODE REVIEW

**Comment by verdan** [comment]
@mgorsk1 would you mind creating this PR against `main` branch instead?

**Comment by mgorsk1** [comment]
good catch @verdan maybe it's time to make main a default one? not quite sure why we would use `master` if it's deprecated

**Comment by verdan** [comment]
@mgorsk1 you also need to rebase your branch with the main branch first.

**Review by verdan — APPROVED** [review]
once the conflicts are resolved.

**Comment by feng-tao** [comment]
+1 on making main branch as default now.

**Pull request merged**
