### PR TITLE
fix: aws session token that is required for neptune to be called

### PR DESCRIPTION
**Pull request by iamtodor**
fix aws session token that is required for neptune to be called

### CODE REVIEW

**Comment by feng-tao** [comment]
```
flake8 .
mypy .
Success: no issues found in 342 source files
isort ./ --check --diff
ERROR: /home/runner/work/amundsen/amundsen/databuilder/example/scripts/sample_neptune_data_cleanup_job.py Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/amundsen/amundsen/databuilder/example/scripts/sample_neptune_data_cleanup_job.py:before	2021-07-05 16:39:31.371871
+++ /home/runner/work/amundsen/amundsen/databuilder/example/scripts/sample_neptune_data_cleanup_job.py:after	2021-07-05 16:46:25.930247
@@ -8,10 +8,11 @@
 import os
 
```

**Comment by feng-tao** [comment]
cc @AndrewCiambrone

**Comment by iamtodor** [comment]
@feng-tao 

sorry, I didn't get the following output:
```
flake8 .
mypy .
Success: no issues found in 342 source files
isort ./ --check --diff
ERROR: /home/runner/work/amundsen/amundsen/databuilder/example/scripts/sample_neptune_data_cleanup_job.py Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/amundsen/amundsen/databuilder/example/scripts/sample_neptune_data_cleanup_job.py:before	2021-07-05 16:39:31.371871
+++ /home/runner/work/amundsen/amundsen/databuilder/example/scripts/sample_neptune_data_cleanup_job.py:after	2021-07-05 16:46:25.930247
@@ -8,10 +8,11 @@
 import os
```
What exactly needs to be changed?
Imports were optimized by hotkey in PyCharm

**Comment by iamtodor** [comment]
@feng-tao the imports were fixed with `isort example/scripts/sample_neptune_data_cleanup_job.py`

**Review by feng-tao — APPROVED** [review]

**Pull request merged**
