### PR TITLE
feat and perf: Add support for Multiple Programmatic Descriptions and Table level Badges

### PR DESCRIPTION
**Pull request by akiratwang**
### Summary of Changes

Hey team, thanks for reviewing this PR! 

Whilst I have heavily modified Amundsen's logic in our company repository (Afterpay, as part of Square/Block), I figured I'd add some of these generalised changes directly into the core repo as they greatly helped us make Amundsen more flexible and deliver our vision.

The motivation originates from https://github.com/amundsen-io/amundsen/discussions/1828 which makes the original code quite convoluted and creates duplicated nodes/records. However, with https://github.com/amundsen-io/amundsen/pull/1877 being an epic speed-up to the original `Neo4JCSV` process (hopefully the PR is merged soon), the original naive method of duplicating `TableMetadata` for multiple programmatic descriptions **does not work**.

The changes here aim to mitigate this issue and allow multiple programmatic descriptions to be added **and** also benefit from the significantly reduced runtime using `APOC`.

Change Log:
- Added support Table level Badges
- Added support for multiple programmatic descriptions to reduce duplicate calls to `TableMetadata`
- Added a sample script under `example/scripts/sample_base_postgres_metadata_extractor` for examples
- Added some extra comments that I felt were useful when reading through the code (they were quite sparse)

Example Changes:
(all sensitive info has been removed)
- Table Badges
image

- Programmatic Descriptions
image

### Tests
The code has been tested and deployed in our prod environment and I am more than happy to have a quick knowledge share on my changes / tests. This consists of over 40 thousand tables and 500,000 thousand columns.

However testing from the core repo side **would be appreciated** as our Amundsen is **greatly modified** and as such, our environment will not capture all test cases.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.
- [x] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by akiratwang** [comment]
Damn can't get this sign-off to work, would be appreciated if a core repo owner can help me resolve it

**Comment by akiratwang** [comment]
@chonyy would appreciate if you can take a look through this PR as well!

**Comment by chonyy** [comment]
Hey @akiratwang , you will have to sign-off **every** commit inorder to pass the DCO 😅
And then you will need a maintainer's approval to get the unit test workflow started.

**Comment by akiratwang** [comment]
> Hey @akiratwang , you will have to sign-off **every** commit in order to pass the DCO 😅 And then you will need a maintainer's approval to get the unit test workflow started.

Wait rip as hahaha. Would it be better off to just create a new branch? I'll resolve the flake8 issues as well in the new PR then.

**Pull request closed without merging**
