### PR TITLE
feat: Generic Usage Extractor with Scala custom sql script for Snowflake

### PR DESCRIPTION
**Pull request by alldoami**
Signed-off-by: Allison Doami <adoami@chanzuckerberg.com>

### Summary of Changes

(replica of https://github.com/amundsen-io/amundsen/pull/1192 after merging fixes)
Implemented a Generic Usage Extractor which utilizes the TableColumnUsage to fill in the popular tables and frequent users feature. CZI uses Snowflake very heavily and because Snowflake does not have table usage built in like BigQuery, I've created a custom sql parser script in Scala that I run in Databricks from an Airflow DAG. The way I calculate popularity is by reading the query logs, parsing what tables are being used within the query, insert a row into the Snowflake popularity table with a unique user, and add one to its score.

### Tests

I would love help to write tests for this! I have this deployed in 5 different Airflow deployments right now and it works great.

### Documentation

A lot of this has come up from a conversation through Slack: https://amundsenworkspace.slack.com/archives/C01857S0V1V/p1619635080092300

Would love to credit @lexisantoro for providing the extractor code! It mainly looks like the snowflake metadata extractor besides the `_get_extract_iter` function.

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes.
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Comment by alldoami** [comment]
@feng-tao @mgorsk1 @sewardgw I reopened this after fixing the signing/commit history issues I was having.

**Comment by sewardgw** [comment]
Looks good overall - just wanted to quickly check to see if there were any unresolved comments from the prior PR that need to be copied over?

**Comment by alldoami** [comment]
yup @sewardgw I think I addressed everything but lmk if there's anything I missed.

**Review by mgorsk1 — APPROVED** [review]
🔥

**Review by sewardgw — APPROVED** [review]
lgtm

**Pull request merged**
