### PR TITLE
Feat: Enable support for Scanning Teradata

### PR DESCRIPTION
**Pull request by DeepakBhatt13**
This PR adds teradata scanner for Amundsen.
Contribution doesn't affect any existing modules/codebase in the repository.

### CODE REVIEW

**Comment by feng-tao** [comment]
CI fails, could you take a look?

**Comment by DeepakBhatt13** [comment]
> CI fails, could you take a look?

**Comment by mgorsk1** [comment]
can you rebase to main? Now PR shows 127 files changed - was that your intention @DeepakBhatt13 ?

**Comment by DeepakBhatt13** [comment]
I will raise fresh PR again

**Comment by DeepakBhatt13** [comment]
Please refer #1791 pull request

**Pull request closed without merging**
