### PR TITLE
feat: add complex delta type rendering on frontend

### PR DESCRIPTION
**Pull request by jroof88**
feat: add complex delta type rendering on frontend

This PR adds support to render complex delta types as nested columns on the UI. This is modeled after the implementation already done for `hive` and `presto` types.

### Summary of Changes
The change here is fairly simple in that it just adds a new `DatabaseId` to the `parser.ts` enum in order to render nested fields nicely on the UI. I also linked the docs for Delta Types above the `SUPPORTED_TYPES` const similar to `hive` and `presto`.

### Tests
I added tests to `parser.spec.ts` to specifically test for delta complex types and make sure they are turn into the proper column rendering.

I also added some sample delta tables to `sample_data/sample_table.csv ` and sample columns to `sample_data/sample_col.csv` with some nested fields and ran the application locally to verify it works:
Screen Shot 2021-07-09 at 11 43 59 AM

I decided to commit the sample data as well since then folks who are testing can see what nested fields look like!

### Documentation
I added a link to delta complex types in the code I wrote to follow the convention of `hive` & `presto`

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
- [X] PR includes a summary of changes.
- [X] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [X] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does

### CODE REVIEW

**Review by sewardgw — APPROVED** [review]
LGTM, squash commits on merge?

As additional food for thought, since you just created this - do you see the value in having explicitly defined parsing processes per data store? When I looked at this a while ago it wasn't completely obvious why Amundsen parses a struct from Hive but wouldn't parse a struct from BigQuery or Delta, in this example. Curious on your thoughts around the value of this data store validation as well vs treating a map, struct, array, etc. as global standards

**Comment by jroof88** [comment]
> do you see the value in having explicitly defined parsing processes per data store?

I'm kind of indifferent honestly. 

On one side, I feel like this should just happen automatically for all complex/nested data types. It's a little frustrating that all it needed was 2 lines of code but now I need to get this merged and a new frontend image cut for it to show up in my production build. 

However on the other side, let's say we onboard a new data store with some fancy nested type syntax and the parser doesn't know what to do with it then the UI could break. I think that's the only benefit of it being opt-in per data store is that we can verify the parser works properly before allowing that data store to have nicely rendered nested/complex types.

**Comment by feng-tao** [comment]
nested types are different or slightly different for each data store which is the reason we have the parsers per store initially. cc @ttannis who built that.

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
thanks @jroof88 , great that you continue adding support for delta!

**Comment by jroof88** [comment]
> thanks @jroof88 , great that you continue adding support for delta!

No problem! Thanks for the swift reviews. Also more PRs to come. I would like to get nested delta types indexed in the search similar to the BigQuery extractor. Stay tuned 👀

**Pull request merged**
